'use strict';

let React = require('react');

module.exports = React.createClass({

	render () {

		return (
			<div className="container about-box">
				<div className="row text-justify">
					<h3><strong>HOW TO MAKE A FRONT END DEVELOPER NAMED MIKE</strong> &bull; FALL IN LOVE WITH LEARNING &bull; GET A TRS-80 FROM UNCLE RICKY &bull; START HITTING THINGS WITH DRUMSTICKS &bull; PLAY LOTS OF VIDEO GAMES &bull; TAKE TWO YEARS OF COMPUTER SCIENCE IN HIGH SCHOOL &bull; SIT NEXT TO FUTURE WIFE IN COMPUTER SCIENCE &bull; MAJOR IN MUSIC EDUCATION IN COLLEGE &bull; TOUR AND PERFORM WITH A DRUM AND BUGLE CORPS &bull; SPEND EQUAL TIME WRITING MUSIC ON A COMPUTER AS PERFORMING IT &bull; GET MARRIED TO YOUR HIGH SCHOOL SWEETHEART &bull; GRADUATE COLLEGE AND TEACH MUSIC FOR OVER A DECADE &bull; MAKE WEBSITES FOR YOUR BAND PROGRAMS &bull; HAVE THREE KIDS ALONG THE WAY &bull; BECOME THE GUARDIAN FOR YOUR BROTHER &bull; REALIZE THAT YOU SPEND AS MUCH TIME FORMATTING AN EMAIL AS TEACHING &bull; START LEARNING MORE CODE &bull; SWITCH GEARS FROM BEING A BAND DIRECTOR TO A WEB DEVELOPER &bull; ENROLL AT A CODE SCHOOL THREE HOURS FROM YOUR FAMILY &bull; KEEP LEARNING AND MAKING AWESOME THINGS.</h3>
				</div>
			</div>
		);
	}
});
